config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  devise_for :customers, skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
    }
  devise_for :admin, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'cart_items', to:'public/cart_items#create'
  delete 'cart_items/:id', to:'public/cart_items#destroy', as: 'destroy_cart_item'
  patch 'cart_items/:id', to:'public/cart_items#update', as: 'update_cart_item'
  get 'cart_items', to:'public/cart_items#index', as: 'cart_item'
  delete 'cart_items', to:'public/cart_items#destroy_all', as: 'destroy_all_cart_item'
  get 'items', to:'public/items#index'
  get 'items/:id', to:'public/items#show', as: 'item'
  get 'customers/my_page', to:'public/customers#show'
  get 'customers/unsubscribe', to:'public/customers#unsubscribe'
  patch 'customers/withdrawal', to:'public/customers#withdrawal'

  root to:'public/homes#top'
  get '/about', to:'public/homes#about'
  get 'orders/new', to:'public/orders#new'
  post 'orders/confirm', to:'public/orders#confirm'
  get 'orders/thanks', to:'public/orders#thanks'
  post 'orders', to:'public/orders#create'
  get 'orders', to:'public/orders#index', as: 'orders_index'
  get 'orders/:id', to:'public/orders#show', as: 'orders_show'
  get 'addresses', to:'public/addresses#index'
  get 'addresses/:id/edit', to:'public/addresses#edit', as: 'edit_addresses'
  post 'addresses', to:'public/addresses#create'
  patch 'addresses/:id', to:'public/addresses#update', as: 'update_addresses'
  delete 'addresses/:id', to:'public/addresses#destroy', as: 'destroy_addresses'
  get 'customers/edit_mypage', to:'public/customers#edit', as:'customers_edit_mypage'
  patch 'customers/update_mypage', to:'public/customers#update', as: 'customers_update_mypage'
  get '/admin',to:'admin/homes#top'
  patch 'admin/order_details/:id', to:'admin/order_details#update', as: 'order_details_update'

  namespace :admin do
    resources :items
    resources :genres
    resources :orders
    resources :customers
  end
  namespace :public do

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  has_many :orders
  attachment:image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def with_tax_price
    (price*1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {not_payment: 0, payment_confirmation: 1, under_construction:2, ready_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {cannot_be_produced: 0, waiting_for_production: 1, in_production: 2, production_completed: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    customer=Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    genre=Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page]).per(10)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    item=Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    order=Order.find(params[:id])
    order.update(order_params)
    if order.status=="payment_confirmation"
      order.order_details.update(making_status:1)
    end
    redirect_to admin_order_path(order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="box2">
  <div class="box3">
    <div class="test"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</div>
    <%= form_with model:@customer,url:admin_customer_path,method: :patch, local:true do |f| %>
    <table cellpadding="5px">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td><%= f.label :image,'氏名' %></td>
        <td>
          <%= f.text_field:last_name %><span style="margin-right: 20px;"></span><%= f.text_field:first_name %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :image,'フリガナ' %></td>
        <td>
          <%= f.text_field:last_name_kana %><span style="margin-right: 20px;"></span><%= f.text_field:first_name_kana %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :image,'郵便番号' %></td>
        <td><%= f.text_field:postal_code %></td>
      </tr>
      <tr>
        <td><%= f.label :image,'住所' %></td>
        <td><%= f.text_field:address, :size=>"60" %></td>
      </tr>
      <tr>
        <td><%= f.label :image,'電話番号' %></td>
        <td><%= f.text_field:telephone_number %></td>
      </tr>
      <tr>
        <td><%= f.label :image,'メールアドレス' %></td>
        <td><%= f.text_field:email %></td>
      </tr>
      <tr>
        <td><%= f.label:is_active,'会員ステータス' %></td>
        <td>
          <%= f.radio_button:is_active, false %>
          <%= f.label:is_active,'有効',value:false %>
          <%= f.radio_button:is_active, true %>
          <%= f.label:is_active,'退会',value:true %>
        </td>
      </tr>
    </table>
    <%= f.submit"変更を保存",class:'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">会員一覧</div>
    <table class="table">
      <thead class="table-light">
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <tr>
          <td scope="row"><%= customer.id %></td>
          <td>
            <%= link_to customer.last_name+customer.first_name, admin_customer_path(customer),class:"test4" %>
          </td>
          <td><%= customer.email %></td>
          <% if customer.is_active == true %>
          <td>
            <font color=silver><b>退会</b></font>
          </td>
          <% else %>
          <td>
            <font color=green><b>有効</b></font>
          </td>
          <% end %>
        </tr>
      </tbody>
      <% end %>
    </table>
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="box2">
  <div class="box3">
    <div class="test"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</div>
    <table cellpadding="5px">
      <tr>
        <td>会員ID</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.last_name %><span style="margin-right: 10px;"></span><%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.last_name_kana%><span style="margin-right: 10px;"></span><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><span style="margin-right: 80px;"></span><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <% if @customer.is_active == true %>
        <td><div class="test5"><span style="margin-right: 80px;"></span>退会</div></td>
        <% else %>
        <td><div class="test3"><span style="margin-right: 80px;"></span>有効</div></td>
        <% end %>
      </tr>
    </table>
    <%= link_to"編集する",edit_admin_customer_path(@customer), class:"btn btn-sm btn-success" %>
    <span style="margin-right: 80px;"></span>
    <%= link_to"注文履歴一覧を見る",admin_path, class:"btn btn-sm btn-primary" %>
  </div>
</div>