config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  devise_for :customers, skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
    }
  devise_for :admin, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'cart_items', to:'public/cart_items#create'
  delete 'cart_items/:id', to:'public/cart_items#destroy', as: 'destroy_cart_item'
  patch 'cart_items/:id', to:'public/cart_items#update', as: 'update_cart_item'
  get 'cart_items', to:'public/cart_items#index', as: 'cart_item'
  delete 'cart_items', to:'public/cart_items#destroy_all', as: 'destroy_all_cart_item'
  get 'items', to:'public/items#index'
  get 'items/:id', to:'public/items#show', as: 'item'
  get 'customers/my_page', to:'public/customers#show'
  get 'customers/unsubscribe', to:'public/customers#unsubscribe'
  patch 'customers/withdrawal', to:'public/customers#withdrawal'

  root to:'public/homes#top'
  get '/about', to:'public/homes#about'
  get 'orders/new', to:'public/orders#new'
  post 'orders/confirm', to:'public/orders#confirm'
  get 'orders/thanks', to:'public/orders#thanks'
  post 'orders', to:'public/orders#create'
  get 'orders', to:'public/orders#index', as: 'orders_index'
  get 'orders/:id', to:'public/orders#show', as: 'orders_show'
  get 'addresses', to:'public/addresses#index'
  get 'addresses/:id/edit', to:'public/addresses#edit', as: 'edit_addresses'
  post 'addresses', to:'public/addresses#create'
  patch 'addresses/:id', to:'public/addresses#update', as: 'update_addresses'
  delete 'addresses/:id', to:'public/addresses#destroy', as: 'destroy_addresses'
  get 'customers/edit_mypage', to:'public/customers#edit', as:'customers_edit_mypage'
  patch 'customers/update_mypage', to:'public/customers#update', as: 'customers_update_mypage'
  get '/admin',to:'admin/homes#top'
  patch 'admin/order_details/:id', to:'admin/order_details#update', as: 'order_details_update'

  namespace :admin do
    resources :items
    resources :genres
    resources :orders
    resources :customers
  end
  namespace :public do

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  has_many :orders
  attachment:image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def with_tax_price
    (price*1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {not_payment: 0, payment_confirmation: 1, under_construction:2, ready_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {cannot_be_produced: 0, waiting_for_production: 1, in_production: 2, production_completed: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    genre=Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page]).per(10)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    item=Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    order=Order.find(params[:id])
    order.update(order_params)
    if order.status=="payment_confirmation"
      order.order_details.update(making_status:1)
    end
    redirect_to admin_order_path(order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">ジャンル編集</div>
    <%= form_with model:@genre,url:admin_genre_path,local:true do |f| %>
      <%= f.label :name,'ジャンル名' %>
      <%= f.text_field:name %>
      <%= f.submit"変更を保存",class:'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">ジャンル一覧・追加</div>
    <%= form_with model:@genre,url:'/admin/genres',local:true do |f| %>
      <%= f.label :name,'ジャンル名' %>
      <%= f.text_field:name %>
      <%= f.submit"新規登録",class:'btn btn-success' %>
    <% end %>
    <table class="table">
      <thead class="table-light">
        <tr>
          <th>ジャンル</th>
        </tr>
      </thead>
      <% @genres.each do |genre| %>
      <tbody>
        <tr>
          <td><%= genre.name %></td>
          <td>
            <%= link_to"編集する",edit_admin_genre_path(genre.id), class:"btn btn-sm btn-success" %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">商品編集</div>
    <%= form_with model:@item,url:admin_item_path, local:true do |f| %>
      <%= f.label :image,'商品画像' %>
      <%= f.attachment_field:image %><br>
      <%= f.label :name,'商品名' %>
      <%= f.text_field:name %><br>
      <%= f.label :introduction,'商品説明' %>
      <%= f.text_area:introduction %><br>
      <%= f.label :genre,'ジャンル' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--" %><br>
      <%= f.label :price,'税抜価格' %>
      <%= f.text_field:price %><a>円</a><br>
      <%= f.label:is_active,'販売ステータス' %>
      <%= f.radio_button:is_active, true %>
      <%= f.label:is_active,'販売中',value:true %>
      <%= f.radio_button:is_active, false %>
      <%= f.label:is_active,'販売停止中',value:false %><br>
      <%= f.submit "変更を保存", class:"btn btn-sm btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="box2">
  <a href="/admin/items/new"class="btn btn-white rounded-circle p-0 shadow-sm text-secondary"style="width:2rem;height:2rem;"role="button">＋</a>
  <div class="box3">
    <div class="test">商品一覧</div>

    <table class="table">
      <thead class="table-light">
        <tr>
          <th scope="col">商品ID</th>
          <th scope="col">商品名</th>
          <th scope="col">税抜価格</th>
          <th scope="col">ジャンル</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <% @items.each do |item| %>
      <tbody>
        <tr>
          <td scope="row">
            <%= item.id %>
          </td>
          <td>
            <%= link_to item.name, admin_item_path(item.id),class:"test4" %>
          </td>
          <td>
            <%= item.price %>
          </td>
          <td>
            <%= item.genre.name %>
          </td>
          <% if item.is_active == true %>
          <td>
            <font color=green><b>販売中</b></font>
          </td>
          <% else %>
          <td>
            <font color=silver><b>販売停止中</b></font>
          </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">商品新規登録</div>
    <%= form_with model:@item,url:'/admin/items',local:true do |f| %>
      <%= f.label :image,'商品画像' %>
      <%= f.attachment_field:image %><br>
      <%= f.label :name,'商品名' %>
      <%= f.text_field:name %><br>
      <%= f.label :introduction,'商品説明' %>
      <%= f.text_area:introduction %><br>
      <%= f.label :genre,'ジャンル' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--" %><br>
      <%= f.label :price,'税抜価格' %>
      <%= f.text_field:price %><a>円</a><br>
      <%= f.label:is_active,'販売ステータス' %>
      <%= f.radio_button:is_active, true %>
      <%= f.label:is_active,'販売中',value:true %>
      <%= f.radio_button:is_active, false %>
      <%= f.label:is_active,'販売停止中',value:false %><br>
      <%= f.submit"新規登録",class:'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="box2">
  <div class="box3">
    <div class="test">商品詳細</div>
    <%= attachment_image_tag @item, :image, format: 'jpeg', size:"250x150" %>
    <table>
      <tr>
        <td>商品名</td>
        <td><%=@item.name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%=@item.introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%=@item.genre.name %></td>
      </tr>
      <tr>
        <td>税込価格<br>(税抜価格)</td>
        <td><% included = @item.price*1.1%><%= included.round %>(<%=@item.price.round%>)円</td>
      </tr>
      <tr>
        <td>販売ステータス</td>
        <td>
          <% if @item.is_active %>
            <font size="4" color="green">販売中</font>
          <% else %>
            <font size="4" color="green">販売停止中</font>
          <% end %>
        </td>
      </tr>
    </table>
    <%= link_to"編集する",edit_admin_item_path(@item.id), class:"btn btn-sm btn-success" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="box2">
  <div class="box3">
    <div class="test1">注文履歴詳細</div>
    <%= form_with model:@order,url:admin_order_path, method: :patch, local:true do |f| %>
    <table>
      <tr>
        <td><b>購入者</b></td>
        <td><span style="margin-right: 10px;"></span><%= link_to @order.customer.last_name+' '+@order.customer.first_name,admin_customer_path(@order.customer_id),class:"test4" %></td>
      </tr>
      <tr>
        <td><b>注文日</b></td>
        <td><span style="margin-right: 10px;"></span><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td><b>配送先</b></td>
        <td><span style="margin-right: 10px;"></span>〒<%= @order.postal_code %><span style="margin-right: 10px;"></span><%= @order.address %><br><span style="margin-right: 10px;"></span><%= @order.name %></td>
      </tr>
      <tr>
        <td><b>支払方法</b></td>
        <td><span style="margin-right: 10px;"></span><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <td><b>注文ステータス</b></td>
        <td>
          <span style="margin-right: 10px;"></span><%= f.select :status, Order.statuses_i18n.invert %>
          <span style="margin-right: 10px;"></span><%= f.submit"更新", class:"btn btn-sm btn-success" %>
        </td>
      </tr>
    </table>
    <% end %>
    <table class="table">
      <thead class="table-light">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </thead>
      <tbody>
      <% @order_details.each do |good| %>
        <tr>
          <td><%= good.item.name %></td>
          <td><%= good.price %></td>
          <td><%= good.amount %></td>
          <td><%= (good.price*good.amount) %></td>
          <%= form_with model:good,url:order_details_update_path(good.id), method: :patch, local:true do |f| %>
          <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %></td>
          <td><%= f.submit"更新", class:"btn btn-sm btn-success" %></td>
          <% end %>
      <% end %>
        </tr>
      </tbody>
    </table>
    <table>
      <tr>
        <td><b>商品合計</b></td>
        <td><span style="margin-right: 10px;"></span><%= (@order.total_payment-800) %>円</td>
      </tr>
      <tr>
        <td><b>送料</b></td>
        <td><span style="margin-right: 10px;"></span><%= @order.shipping_cost %>円</td>
      </tr>
      <tr>
        <td><b>請求金額合計</b></td><td><span style="margin-right: 10px;"></span><b><%= @order.total_payment %>円</b></td>
      </tr>
    </table>
  </div>
</div>