config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  devise_for :customers, skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
    }
  devise_for :admin, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'cart_items', to:'public/cart_items#create'
  delete 'cart_items/:id', to:'public/cart_items#destroy', as: 'destroy_cart_item'
  patch 'cart_items/:id', to:'public/cart_items#update', as: 'update_cart_item'
  get 'cart_items', to:'public/cart_items#index', as: 'cart_item'
  delete 'cart_items', to:'public/cart_items#destroy_all', as: 'destroy_all_cart_item'
  get 'items', to:'public/items#index'
  get 'items/:id', to:'public/items#show', as: 'item'
  get 'customers/my_page', to:'public/customers#show'
  get 'customers/unsubscribe', to:'public/customers#unsubscribe'
  patch 'customers/withdrawal', to:'public/customers#withdrawal'

  root to:'public/homes#top'
  get '/about', to:'public/homes#about'
  get 'orders/new', to:'public/orders#new'
  post 'orders/confirm', to:'public/orders#confirm'
  get 'orders/thanks', to:'public/orders#thanks'
  post 'orders', to:'public/orders#create'
  get 'orders', to:'public/orders#index', as: 'orders_index'
  get 'orders/:id', to:'public/orders#show', as: 'orders_show'
  get 'addresses', to:'public/addresses#index'
  get 'addresses/:id/edit', to:'public/addresses#edit', as: 'edit_addresses'
  post 'addresses', to:'public/addresses#create'
  patch 'addresses/:id', to:'public/addresses#update', as: 'update_addresses'
  delete 'addresses/:id', to:'public/addresses#destroy', as: 'destroy_addresses'
  get 'customers/edit_mypage', to:'public/customers#edit', as:'customers_edit_mypage'
  patch 'customers/update_mypage', to:'public/customers#update', as: 'customers_update_mypage'
  get '/admin',to:'admin/homes#top'
  patch 'admin/order_details/:id', to:'admin/order_details#update', as: 'order_details_update'

  namespace :admin do
    resources :items
    resources :genres
    resources :orders
    resources :customers
  end
  namespace :public do

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :addresses
  has_many :orders
  attachment:image
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def with_tax_price
    (price*1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {not_payment: 0, payment_confirmation: 1, under_construction:2, ready_to_ship:3, shipped:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {cannot_be_produced: 0, waiting_for_production: 1, in_production: 2, production_completed: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    genre=Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page]).per(10)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    item=Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!--<body class="d-flex flex-column vh-100">-->
  <body>
    <div class="container-fluid">
    <header style="border:solid thin black;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag'logo.jpg', :size=>'200x60' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li class="nav-item">
              <a href="/customers/my_page"class="btn btn-outline-secondary p-1 text-dark"style="width:6rem;height:2rem;"role="button">マイページ</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/items"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">商品一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/cart_items"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">カート</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-outline-secondary p-1 text-dark" %>

            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <a href="/admin/items"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">商品一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/admin/customers"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">会員一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/admin"class="btn btn-outline-secondary p-1 text-dark"style="width:7rem;height:2rem;"role="button">注文履歴一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/admin/genres"class="btn btn-outline-secondary p-1 text-dark"style="width:7rem;height:2rem;"role="button">ジャンル一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-secondary p-1 text-dark" %>
            </li>
            <% else %>
            <li class="nav-item">
              <a href="/about"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">About</a>
            </li>
            <li class="nav-item">
             <span style="margin-right: 20px;"></span><a href="/items"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">商品一覧</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/customers/sign_up"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">新規登録</a>
            </li>
            <li class="nav-item">
              <span style="margin-right: 20px;"></span><a href="/customers/sign_in"class="btn btn-outline-secondary p-1 text-dark"style="width:5rem;height:2rem;"role="button">ログイン</a>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <footer></footer>
    </div>
  </body>
</html>